# calico
# directories
network_plugin_bin_dir: /opt/cni/bin
# paths
calico_conf_path: "{{network_plugin_dir}}/10-calico.conf"
network_environment_path: "/etc/network-environment"

#file modes
calico_executable_mode: 0775

dafault_cidr: 192.168.0.0/16
