---
  # add ingress label to nodes
  - name: label ingress nodeSelector
    command: kubectl label nodes {% for host in groups['ingress'] %}{{ host }} {% endfor %} ingress=true --overwrite

  # TODO verify ingress is running after apply
  - name: copy default-backend.yaml to remote
    template:
      src: default-backend.yaml
      dest: /tmp/default-backend.yaml
  - name: start default-backend serivce
    command: kubectl apply -f /tmp/default-backend.yaml

  - name: copy nginx-ingress-controller.yaml to remote
    template:
      src: nginx-ingress-controller.yaml
      dest: /tmp/nginx-ingress-controller.yaml
  - name: start default-backend serivce
    command: kubectl apply -f /tmp/nginx-ingress-controller.yaml
