---
  # TODO notify user of the port, ingress
  - name: copy kubernetes-dns.yaml to remote
    template:
      src: kubernetes-dns.yaml
      dest: /tmp/kubernetes-dns.yaml
  - name: start kubernetes-dns service
    command: kubectl apply -f /tmp/kubernetes-dns.yaml
    register: out

  - debug: var=out.stdout_lines
