---
  # TODO notify user of the port, ingress
  - name: copy kubernetes-dns.yaml to remote
    template:
      src: kubernetes-dns.yaml
      dest: /tmp/kubernetes-dns.yaml
  - name: start kubernetes-dns service
    command: kubectl apply -f /tmp/kubernetes-dns.yaml
    register: out
  - name: verify kubernetes-dns service is running
    command: kubectl get rc kube-dns-v18 --namespace kube-system -o jsonpath='{.status.readyReplicas}'
    register: readyReplicas
    until: readyReplicas.stdout|int > 0
    retries: 15
    delay: 10

  - debug: var=out.stdout_lines
