---
  # kube-apiserver
  - name: copy kube-apiserver.service to remote
    template:
      src: kube-apiserver.service.j2
      dest: "{{ kubernetes_service_dir }}/kube-apiserver.service"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"
    notify:
      - reload services
      - enable kube-apiserver
      - restart kube-apiserver service
      - verify kube-apiserver is running

  # force_apiserver_restart=true to force restart
  - name: force restart kube-apiserver
    command: /bin/true
    notify:
      - enable kube-apiserver
      - restart kube-apiserver service
      - verify kube-apiserver is running
    when: force_apiserver_restart is defined and force_apiserver_restart|bool == true
