---
  - include: ../validate-pod/tasks/get-pods.yaml component="kube-apiserver"
  - name: vaildate kube-apiserver pods
    include: ../validate-pod/tasks/validate-pod.yaml
    with_items:
      - "{{ the_pods.stdout.split(' ') }}"

  - include: ../validate-pod/tasks/get-pods.yaml component="kube-scheduler"
  - name: vaildate kube-scheduler pods
    include: ../validate-pod/tasks/validate-pod.yaml
    with_items:
      - "{{ the_pods.stdout.split(' ') }}"

  - include: ../validate-pod/tasks/get-pods.yaml component="kube-controller-manager"
  - name: vaildate kube-controller-manager pods
    include: ../validate-pod/tasks/validate-pod.yaml
    with_items:
      - "{{ the_pods.stdout.split(' ') }}"
