---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable calico-node
    command: systemctl enable calico-node.service
  - name: restart calico-node service
    service:
      name: calico-node.service
      state: restarted
      enabled: yes
  - name: verify calico-node is running
    command: systemctl status calico-node
    register: running
    until: running|success
    retries: 3
    delay: 5
