---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-controller-manager
    command: systemctl enable kube-controller-manager.service
  - name: restart kube-controller-manager service
    service:
      name: kube-controller-manager.service
      state: restarted
      enabled: yes

  # verify service
  - name: verify kube-controller-manager is running
    command: systemctl status kube-controller-manager
    changed_when: false
