---
  # kube-scheduler
  - name: copy kube-scheduler.service to remote
    template:
      src: kube-scheduler.service.j2
      dest: "{{ kubernetes_service_dir }}/kube-scheduler.service"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kuberntes_service_mode }}"
    notify:
      - reload services
      - enable kube-scheduler
      - restart kube-scheduler service
      - verify kube-scheduler is running

  # force_scheduler_restart=true to force restart
  - name: force restart scheduler
    command: /bin/true
    notify:
      - enable kube-scheduler
      - restart kube-scheduler service
      - verify kube-scheduler is running
    when: force_scheduler_restart is defined and force_scheduler_restart|bool == true
