---
  # download kubernetes binaries
  - name: download kube-scheduler - v{{ kubernetes_version }}
    get_url:
      url: "{{ kubernetes_binary_path }}/kube-scheduler"
      dest: "{{ bin_dir }}"
      mode: "{{ kubernetes_executable_mode }}"

  # kube-scheduler
  - name: copy kube-scheduler.service to remote
    template:
      src: kube-scheduler.service.j2
      dest: "{{ kubernetes_service_dir }}/kube-scheduler.service"
      owner: "{{ kuberntes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kuberntes_service_mode }}"
    notify:
      - reload services
      - enable kube-scheduler
      - start kube-scheduler service
      - verify kube-scheduler is running
      - report status of kube-scheduler
