# kubernets-master-install
kubernetes_install_dir: /etc/kubernetes
kubernetes_service_path: "{{ init_system_dir }}"
kubernetes_version: 1.3.4
kubernetes_token_atuh_path: /var/lib/kubernetes/tokens.csv
kubernetes_authorization_policy_path: /var/lib/kubernetes/authorization-policy.json
kubernetes_kubeconfig_path: /var/lib/kubelet/kubeconfig
kubernetes_network_plugin_dir: /etc/cni/net.d
kubernetes_executable_mode: 0775
kubernetes_binary_path: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64
calico_version: 0.20.0
calico_binary_path: https://github.com/projectcalico/calico-containers/releases/download/v{{ calico_version }}/calicoctl
calico_executable_mode: 0775
network_environment_mode: 0660
etcd_k8s_client_port: 2379
etcd_networking_client_port: 6666
kuberntes_owner: root
kubernetes_group: root
kuberntes_service_mode: 0664
kubernetes_schedulable: false

# certificates
kubernetes_certificates_ca_file_name: ca.pem
kubernetes_certificates_cert_file_name: kubenode.pem
kubernetes_certificates_key_file_name: kubenode-key.pem
kubernetes_certificates_ca_path: "{{ kubernetes_install_dir }}/{{ kubernetes_certificates_ca_file_name }}"
kubernetes_certificates_cert_path: "{{ kubernetes_install_dir }}/{{ kubernetes_certificates_cert_file_name }}"
kubernetes_certificates_key_path: "{{ kubernetes_install_dir }}/{{ kubernetes_certificates_key_file_name }}"
kubernetes_certificates_owner: root
kubernetes_certificates_group: root
kubernetes_certificates_mode: 0660
