---
# download and install etcd and etcdctl
- name: create {{ etcd_install_path }} directory
  file: path={{ etcd_install_path }} state=directory
- name: download and untar {{ etcd_install_bin_name }}
  unarchive: src={{ etcd_install_binary_download_path }} dest={{ temprary_download_dir }} remote_src=yes copy=no
- name: copy {{ etcd_install_bin_name }} binaries
  copy: src={{ etcd_install_binary_untared_dir }}/etcd dest={{ bin_dir }}/{{ etcd_install_bin_name }} remote_src=True owner={{ etcd_install_executable_owner }} group={{ etcd_install_executable_group }} mode={{ etcd_install_executable_mode }}
- name: copy {{ etcdctl_install_bin_name }} binaries
  copy: src={{ etcd_install_binary_untared_dir }}/etcdctl dest={{ bin_dir }}/{{ etcdctl_install_bin_name }} remote_src=True owner={{ etcd_install_executable_owner }} group={{ etcd_install_executable_group }} mode={{ etcd_install_executable_mode }}

# install and start etcd service
- name: copy {{ etcd_service_file }} to remote
  template: src={{ etcd_service_template_name }} dest={{ etcd_service_path }} owner={{ etcd_service_owner }} group={{ etcd_service_group }} mode={{ etcd_service_mode }}
- name: enable {{ etcd_service_path }}
  command: systemctl enable {{ etcd_service_path }}
- name: start {{ etcd_service_name }} service
  service: name={{ etcd_service_name }} state=started enabled=yes
