---
  # setup directories
  - name: create {{ kubernetes_kubectl_config_dir }} directory
    file: path={{ kubernetes_kubectl_config_dir }} state=directory

  - name: copy kubeconfig to remote
    template: src=kubeconfig.j2 dest={{ kubernetes_kubeconfig_path }}
