---
  # kubelet
  - name: copy kubelet.service to remote
    template:
      src: kubelet.service.j2
      dest: "{{ kubernetes_service_dir }}/kubelet.service"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kuberntes_service_mode }}"
    notify:
      - reload services
      - enable kubelet
      - restart kubelet service
      - verify kubelet is running

  # force_kubelet_restart=true to force restart
  - name: force restart kubelet
    command: /bin/true
    notify:
      - enable kubelet
      - restart kubelet service
      - verify kubelet is running
    when: force_kubelet_restart is defined and force_kubelet_restart|bool == true
