---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable docker
    command: systemctl enable {{ docker_service_file }}
  - name: restart docker service
    service:
      name: "docker"
      state: restarted
      enabled: yes
