---
  # - name: docker installed
  #   file: path={{ docker_installed_path }} state=touch
  - name: reload services
    command: systemctl daemon-reload
  - name: enable docker
    command: systemctl enable "docker.service"
  - name: restart docker service
    service:
      name: "docker"
      state: restarted
      enabled: yes
