---
  - name: create {{ network_plugin_dir }} directory
    file:
      path: "{{ network_plugin_dir }}"
      state: directory
      
  - name: create /etc/weave directory
    file:
      path: "{{ weave_dir }}"
      state: directory
  - name: copy weave.yaml to remote
    template:
      src: weave.yaml
      dest: "{{weave_dir}}/weave.yaml"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"

    # label nodes that will have weave isntalled
  - name: label nodes for weave
    command: kubectl label nodes {% for host in play_hosts %}{{ host }} {% endfor %} kismatic/cni-provider=weave --overwrite --kubeconfig {{ kubernetes_kubeconfig_path }}
    run_once: true

  - name: start weave containers
    command: kubectl apply -f /etc/weave/weave.yaml --kubeconfig {{ kubernetes_kubeconfig_path }}
    run_once: true
