---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-scheduler
    command: systemctl enable kube-scheduler.service
  - name: start kube-scheduler service
    service: name=kube-scheduler.service state=started enabled=yes

  # verify service
  - name: verify kube-scheduler is running
    command: systemctl status kube-scheduler
    ignore_errors: yes
    changed_when: false
    register: service_kube_scheduler_status
  - name: report status of kube-scheduler
    fail:
      msg: |
        Service kube-scheduler is not running.
        Output of `systemctl status kube-scheduler`:
          {{ service_kube_scheduler_status.stdout }}
          {{ service_kube_scheduler_status.stderr }}
    when: service_kube_scheduler_status | failed
