---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-scheduler
    command: systemctl enable kube-scheduler.service
  - name: restart kube-scheduler service
    service:
      name: kube-scheduler.service
      state: restarted
      enabled: yes
  - name: verify kube-scheduler is running
    command: systemctl status kube-scheduler
    register: running
    until: running|success
    retries: 3
    delay: 5
