---
    # setup directories
    - name: create {{ docker_install_dir }}
      file:
        path: "{{ docker_install_dir }}"
        state: directory
    # copy certificates
    - name: copy {{ docker_certificates_cert_file_name }}
      copy:
        src: "{{ tls_directory }}/docker.pem"
        dest: "{{ docker_certificates_cert_path }}"
        owner: "{{ docker_certificates_owner }}"
        group: "{{ docker_certificates_group }}"
        mode: "{{ docker_certificate_mode }}"
    - name: copy {{ docker_certificates_key_file_name }}
      copy:
        src: "{{ tls_directory }}/docker-key.pem"
        dest: "{{ docker_certificates_key_path }}"
        owner: "{{ docker_certificates_owner }}"
        group: "{{ docker_certificates_group }}"
        mode: "{{ docker_certificate_mode }}"
    - name: restart docker service
      service:
        name: "docker"
        state: restarted
        enabled: yes

    # Setup Docker Registry
    - name: verify if docker registry container is running
      shell: docker ps | grep registry
      register: docker_ps_registry
      ignore_errors: yes # dont fail, next task will start it if not running
      changed_when: false

    - name: load docker registry from file
      command: docker load --input /opt/images/registry.tar
      when: docker_ps_registry|failed

    - name: start docker registry container
      command: docker run -d -p 5000:{{ docker_registry_port }} --restart=always --name registry -v {{docker_install_dir}}:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/{{docker_certificates_cert_file_name}} -e REGISTRY_HTTP_TLS_KEY=/certs/{{docker_certificates_key_file_name}} registry:2
      when: docker_ps_registry|failed

    - name: load docker images
      command: docker load -i /opt/images/{{ item }}.tar
      with_items:
       - calico
       - kube-policy-controller
       - kubedns
       - kube-dnsmasq
       - exechealthz
       - kubernetes-dashboard
       - pause

    - name: tag docker images
      command: docker tag {{ item }}
      with_items:
        - "{{calico_node_orig_img}} {{calico_node_priv_img}}"
        - "{{calico_kube_policy_controller_orig_img}} {{calico_kube_policy_controller_priv_img}}"
        - "{{kubedns_orig_img}} {{kubedns_priv_img}}"
        - "{{kube_dnsmasq_orig_img}} {{kube_dnsmasq_priv_img}}"
        - "{{exechealthz_orig_img}} {{exechealthz_priv_img}}"
        - "{{kubernetes_dashboard_orig_img}} {{kubernetes_dashboard_priv_img}}"
        - "{{pause_orig_img}} {{pause_priv_img}}"

    - name: push docker image to private registry
      command: docker push {{ item }}
      with_items:
        - "{{calico_node_priv_img}}"
        - "{{calico_kube_policy_controller_priv_img}}"
        - "{{kubedns_priv_img}}"
        - "{{kube_dnsmasq_priv_img}}"
        - "{{exechealthz_priv_img}}"
        - "{{kubernetes_dashboard_priv_img}}"
        - "{{pause_priv_img}}"
