# directories
kubernetes_lib_dir: /var/lib/kubernetes
# paths
kubernetes_token_auth_path: "{{kubernetes_lib_dir}}/tokens.csv"
kubernetes_authorization_policy_path: "{{kubernetes_lib_dir}}/authorization-policy.json"
