---
  - name: create /etc/kubernetes/specs directory
    file:
      path: "{{ kubernetes_spec_dir }}"
      state: directory
  # TODO notify user of the port, ingress
  - name: copy policy-controller.yaml to remote
    template:
      src: policy-controller.yaml
      dest: "{{ kubernetes_spec_dir }}/policy-controller.yaml"
  - name: start calico policy controller
    command: kubectl apply -f {{ kubernetes_spec_dir }}/policy-controller.yaml
    register: out

  - debug: var=out.stdout_lines
