---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kubelet
    command: systemctl enable kubelet.service
  - name: start kubelet service
    service: name=kubelet.service state=started enabled=yes
