---
  # verify specified cluster for minimum requirements
  # OS specific reqs
  - name: verify systemd
    fail: msg="systemd is required"
    when: ansible_service_mgr != "systemd"
    changed_when: false

  # netowrking reqs
  - name: ping all hosts
    command: ping -c 2 {{ hostvars[item].internal_ipv4 }}
    when: hostvars[item].internal_ipv4 is defined
    with_items: "{{ groups['all'] }}"
    changed_when: false

  - name: verify etcd-k8s client port 2379 is open
    shell: "! netstat -na | grep ':2379'"
    changed_when: false
    when: "'etcd' in group_names"

  - name: verify etcd-k8s peer port 2380 is open
    shell: "! netstat -na | grep ':2380'"
    changed_when: false
    when: "'etcd' in group_names"

  - name: verify etcd-networking client port 6666 is open
    shell: "! netstat -na | grep ':6666'"
    changed_when: false
    when: "'etcd' in group_names"

  - name: verify etcd-networking peer port 6660 is open
    shell: "! netstat -na | grep ':6660'"
    changed_when: false
    when: "'etcd' in group_names"

  - name: verify kubernetes insecure port {{ kubernetes_master_insecure_port }} is open
    shell: "! netstat -na | grep ':{{ kubernetes_master_insecure_port }}'"
    changed_when: false
    when: "'master' in group_names"

  - name: verify kubernetes secure port {{ kubernetes_master_secure_port }} is open
    shell: "! netstat -na | grep ':{{ kubernetes_master_secure_port }}'"
    changed_when: false
    when: "'master' in group_names"

  # list from https://github.com/kubernetes/kubernetes/issues/26093
  - include: roles/preflight/tasks/command.yaml utility=glibc

  - include: roles/preflight/tasks/command.yaml utility=iptables

  - include: roles/preflight/tasks/command.yaml utility=iptables-restore

  - include: roles/preflight/tasks/command.yaml utility=iptables-save

  - include: roles/preflight/tasks/command.yaml utility=ip

  - include: roles/preflight/tasks/command.yaml utility=nsenter

  - include: roles/preflight/tasks/command.yaml utility=mount

  - include: roles/preflight/tasks/command.yaml utility=unmount

  - include: roles/preflight/tasks/command.yaml utility=socat
