---
  - name: get etcd server version
    command: curl --cert {{ etcd_certificates.etcd_client }} --key {{ etcd_certificates.etcd_client_key }} --cacert {{ etcd_certificates.ca }} https://{{ inventory_hostname }}:{{ etcd_service_client_port }}/version
    register: current_etcd_version

  - name: check if etcd needs to be upgraded
    set_fact:
      etcd_needs_upgrade: "{{ (current_etcd_version.stdout | from_json)['etcdserver'] != etcd_version }}"
