---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-proxy
    command: systemctl enable kube-proxy.service
  - name: restart kube-proxy service
    service:
      name: kube-proxy.service
      state: restarted
      enabled: yes
  - name: verify kube-proxy is running
    command: systemctl status kube-proxy
    register: running
    until: running|success
    retries: 3
    delay: 5
