---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-proxy
    command: systemctl enable kube-proxy.service
  - name: start kube-proxy service
    service: name=kube-proxy.service state=started enabled=yes
