---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-proxy
    command: systemctl enable kube-proxy.service
  - name: restart kube-proxy service
    service:
      name: kube-proxy.service
      state: restarted
      enabled: yes

  # verify service
  - name: verify kube-proxy is running
    command: systemctl status kube-proxy
    retries: 5
    delay: 3
