---
  # - name: install the latest version of bridge-utils
  #   package: name=bridge-utils state=latest
  # # install Docker using official https://get.docker.com/ script
  # - name: create {{ docker_install_dir }} directory
  #   file:
  #     path: "{{ docker_install_dir }}"
  #     state: directory
  # - name: start docker service # create a signal file after successful install
  #   command: /bin/true #docker.sh creates={{ docker_installed_path }}
  #   notify:
  #     #- docker installed
  #     - reload services
  #     - enable docker
  #     - restart docker service

  - name: reload services
    command: systemctl daemon-reload
  - name: enable docker
    command: systemctl enable "docker.service"
  - name: restart docker service
    service:
      name: "docker"
      state: restarted
      enabled: yes

  # verify that Docker installed succesfully and is running
  - name: verify docker is installed
    command: docker ps
