---
  - name: install the latest version of bridge-utils
    package: name=bridge-utils state=latest
  # install Docker using official https://get.docker.com/ script
  - name: create {{ docker_install_dir }} directory
    file:
      path: "{{ docker_install_dir }}"
      state: directory
  - name: install lastest version of docker # create a signal file after successful install
    script: docker.sh creates={{ docker_installed_path }}
    notify:
      - docker installed
      - reload services
      - enable {{ docker_service_path }}
      - restart {{ docker_service_name }} service
