---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable docker
    command: systemctl enable "docker.service"
  - name: restart docker service
    service:
      name: "docker"
      state: restarted
      enabled: yes

  # verify that Docker installed succesfully and is running
  - name: verify docker is installed
    command: docker ps
