---
  - hosts: master[0]
    name: "{{step | default()}}Add-On Configure Calico Network Policy"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - addon-network-policy
