---
  - hosts: master[0]
    any_errors_fatal: true
    name: "Add-On Logging"
    remote_user: root
    become: yes
    run_once: true

    roles:
      - role: addon-logging
        when: pv_logging_nfs_server_ip is defined and pv_logging_nfs_dir is defined and pv_logging_storage_size is defined
