---
  - hosts: master[0]
    name: Add-On Docker Registry
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - role: addon-docker-registry
        when: enable_docker_registry is defined and enable_docker_registry == "true"
