---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Deploy Cluster Certificates"
    become: yes
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubenode-cert
      - role: docker-registry-cert
        when: configure_docker_with_private_registry is defined and configure_docker_with_private_registry|bool == true
