---
  - hosts: master
    name: "{{step | default()}}Install Kubernetes Controller Manager "
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubeconfig
      - controller-manager
