  - hosts: etcd
    any_errors_fatal: true
    name: "{{ play_name | default('Migrate Kubernetes Etcd Cluster to v3') }}"
    serial: 1 # need to always do this serially
    become: yes
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-k8s.yaml

    roles:
      - role: etcd-migrate
        when: upgrading is defined and upgrading|bool == true
