---
  - hosts: etcd
    name: Install networking etcd cluster
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-networking.yaml

    roles:
      - etcd-cert
      - etcd
