---
  # update hosts files of all nodes
  - hosts: all
    any_errors_fatal: true
    name: "Update Hosts File"
    remote_user: root
    become_method: sudo

    roles:
      - role: hosts
        when: modify_hosts_file is defined and modify_hosts_file == "true"
