---
  # update hosts files of all nodes
  - hosts: all
    name: Update Hosts File
    remote_user: root
    become_method: sudo

    roles:
      - role: hosts
        when: modify_hosts_file is defined and modify_hosts_file == "true"
