---
  - hosts: master
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/kubelet-master.yaml

    roles:
      - network-environment
      - kubeconfig
      - kubelet
