---
  - hosts: master:!worker
    name: "{{step | default()}}Install Kubernetes Kubelet on Master Nodes"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/kubelet-master.yaml

    roles:
      - network-environment
      - kubeconfig
      - kubelet
