---
  - hosts: worker
    name: Install Kubelet on Worker nodes
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/kubelet-worker.yaml

    roles:
      - network-environment
      - kubeconfig
      - kubelet
