---
  - hosts: worker:master
    name: "{{step | default()}}Deploy Cluster Certificates"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubenode-cert
