---
  - name: "Drain Node"
    hosts: master:worker:ingress:storage
    serial: 1
    tasks:
      - name: "Run kubectl drain"
        command: "kubectl drain --ignore-daemonsets --force --delete-local-data {{ inventory_hostname|lower }}"
        # --force is required for static pods, --delete-local-data is required for pods with emptyDir
