---
  - hosts: "{{ hosts | default('master:worker') }}"
    name: "{{step | default()}}Install Kubernetes Proxy"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubeconfig
      - proxy
