---
  - hosts: master
    any_errors_fatal: true
    name: Smoke Test Master Node
    remote_user: root
    become: yes
    serial: 1
    vars_files:
      - group_vars/all.yaml

    roles:
      - smoketest
