---
  - hosts: master:!worker
    any_errors_fatal: true
    name: "Smoke test Master Nodes"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/kubelet-master.yaml

    roles:
      - smoketest