---
  - hosts: storage
    any_errors_fatal: true
    name: "Bootstrap Persistent Storage Cluster"
    remote_user: root
    become: yes

    environment:
      https_proxy: "{{ https_proxy }}"
      http_proxy: "{{ http_proxy }}"
      no_proxy: "{{ no_proxy }}"

    roles:
      - role: packages-glusterfs
        when: allow_package_installation|bool == true
      - glusterfs

  - hosts: master
    any_errors_fatal: true
    name: "Create NFS service on the cluster"
    run_once: true
    remote_user: root
    become: yes
    roles:
      - glusterfs-k8s
