---
  - hosts: master
    any_errors_fatal: false # TODO is this what we want, continue on other nodes
    name: "Validate Kubernetes Control Plane is Running"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - validate-control-plane-node
