---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Start Weave Network Components') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: download networking images
        command: docker pull {{ item }}
        with_items:
          - "{{ weave_img }}"
          - "{{ weave_npc_img }}"
    
    roles:
      - weave
