---
  - name: copy calicoctl.cfg to remote
    template:
      src: calicoctl.cfg
      dest: "{{ calicoctl_conf_path }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ network_environment_mode }}"

  - name: copy ippool.yaml to remote
    template:
      src: ippool.yaml
      dest: "{{ calico_ippool_path }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ network_environment_mode }}"

  - name: add pods CIDR - {{ kubernetes_pods_cidr }}
    command: docker run -i{% if modify_hosts_file is defined and modify_hosts_file|bool == true %} -v /etc/hosts:/etc/hosts{% endif %} -v /etc/kubernetes:/etc/kubernetes -v {{ calicoctl_conf_path }}:{{ calicoctl_conf_path }} -v {{ calico_ippool_path }}:{{ calico_ippool_path }} {{ calico_ctl_img }} apply -f {{ calico_ippool_path }}
