---
  # Load docker images into private registry
  - name: load docker images
    command: docker load -i /opt/images/{{ item }}.tar
    with_items:
     - kube-policy-controller
     - kubedns
     - kube-dnsmasq
     - exechealthz
     - kubernetes-dashboard
     - defaultbackend
     - nginx-ingress-controller

  - name: tag docker images
    command: docker tag {{ item }}
    with_items:
      - "{{calico_kube_policy_controller_orig_img}} {{calico_kube_policy_controller_priv_img}}"
      - "{{kubedns_orig_img}} {{kubedns_priv_img}}"
      - "{{kube_dnsmasq_orig_img}} {{kube_dnsmasq_priv_img}}"
      - "{{exechealthz_orig_img}} {{exechealthz_priv_img}}"
      - "{{kubernetes_dashboard_orig_img}} {{kubernetes_dashboard_priv_img}}"
      - "{{defaultbackend_orig_img}} {{defaultbackend_priv_img}}"
      - "{{nginx_ingress_controller_orig_img}} {{nginx_ingress_controller_priv_img}}"

  - name: push docker image to private registry
    command: docker push {{ item }}
    with_items:
      - "{{calico_kube_policy_controller_priv_img}}"
      - "{{kubedns_priv_img}}"
      - "{{kube_dnsmasq_priv_img}}"
      - "{{exechealthz_priv_img}}"
      - "{{kubernetes_dashboard_priv_img}}"
      - "{{defaultbackend_priv_img}}"
      - "{{nginx_ingress_controller_priv_img}}"
