- debug:
    var: item.1
- set_fact:
    index: "{{item.0}}"
    host: "{{item.1.host}}"
    path: "{{item.1.path}}"

- name: mount share read/write
  mount: 
    name: "/mnt/test-{{index}}"
    src: "{{host}}:{{path}}"
    fstype: nfs 
    state: mounted

- name: Grab share size
  shell: "df /mnt/test-{{index}} | grep -oP '\\K\\d+(?=\\s+\\d+%)'"
  register: nfs_size_blob

- debug: 
    var: nfs_size_blob

- set_fact:
    nfs_size: "{{nfs_size_blob.stdout}}"

- debug: 
    var: nfs_size

- name: mount share read/write
  mount: 
    name: "/mnt/test-{{index}}"
    src: "{{host}}:{{path}}"
    fstype: nfs 
    state: unmounted

- name: copy PV.yaml to remote
  template:
    src: add-persistent-volume.yaml
    dest: /tmp/add-persistent-volume-{{index}}.yaml

- name: apply PV.yaml
  command: kubectl apply -f /tmp/add-persistent-volume-{{index}}.yaml

