---
  # download kubernetes binaries
  - name: download kube-controller-manager - v{{ kubernetes_version }}
    get_url:
      url: "{{ kubernetes_binary_path }}/kube-controller-manager"
      dest: "{{ bin_dir }}"
      mode: "{{ kubernetes_executable_mode }}"

  # kube-controller-manager
  - name: copy kube-controller-manager.service to remote
    template:
      src: kube-controller-manager.service.j2
      dest: "{{ kubernetes_service_dir }}/kube-controller-manager.service"
      owner: '{{ kuberntes_owner }}'
      group: "{{ kubernetes_group }}"
      mode: "{{ kuberntes_service_mode }}"
    notify:
      - reload services
      - enable kube-controller-manager
      - restart kube-controller-manager service
      - verify kube-controller-manager is running
      - report status of kube-controller-manager
