---
  # download kubernetes binaries
  # - name: download kube-controller-manager - {{ kubernetes_version }}
  #   get_url:
  #     url: "{{ kubernetes_binary_path }}/kube-controller-manager"
  #     dest: "{{ bin_dir }}"
  #     mode: "{{ kubernetes_executable_mode }}"

  # kube-controller-manager
  - name: copy kube-controller-manager.service to remote
    template:
      src: kube-controller-manager.service.j2
      dest: "{{ kubernetes_service_dir }}/kube-controller-manager.service"
      owner: '{{ kubernetes_owner }}'
      group: "{{ kubernetes_group }}"
      mode: "{{ kuberntes_service_mode }}"
    notify:
      - reload services
      - enable kube-controller-manager
      - restart kube-controller-manager service
      - verify kube-controller-manager is running

  # force_controller_manager_restart=true to force restart
  - name: force restart controller-manager
    command: /bin/true
    notify:
      - enable kube-controller-manager
      - restart kube-controller-manager service
      - verify kube-controller-manager is running
    when: force_controller_manager_restart is defined and force_controller_manager_restart == "true"
